/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech) (5.1.0).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package com.globant.tc.scooter.accounts.api;

import com.globant.tc.scooter.accounts.entity.AccountEntity;
import com.globant.tc.scooter.accounts.model.CreditsToAccount;
import com.globant.tc.scooter.accounts.services.AddCreditsToAccountApiDelegate;
import io.swagger.annotations.*;
import org.springframework.http.ResponseEntity;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.*;

import javax.validation.Valid;

@javax.annotation.Generated(value = "org.openapitools.codegen.languages.SpringCodegen", date = "2022-03-11T21:44:36.143+05:00[Asia/Karachi]")
@Validated
@Api(value = "addCreditsToAccount", description = "the addCreditsToAccount API")
public interface AddCreditsToAccountApi {

    default AddCreditsToAccountApiDelegate getDelegate() {
        return new AddCreditsToAccountApiDelegate() {};
    }

    /**
     * POST /addCreditsToAccount : Add Credits To Account.
     * Optional extended description in CommonMark or HTML.
     *
     * @param inlineObject1  (required)
     * @return Operation success (status code 200)
     */
    @ApiOperation(value = "Add Credits To Account.", nickname = "addCreditsToAccountPost", notes = "Optional extended description in CommonMark or HTML.", tags={  })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "Operation success") })
    @PostMapping(
        value = "/addCreditsToAccount",
        consumes = { "application/json" }
    )
    default ResponseEntity<AccountEntity> addCreditsToAccountPost(@ApiParam(value = "" ,required=true )  @Valid @RequestBody CreditsToAccount inlineObject1) {
        return getDelegate().addCreditsToAccountPost(inlineObject1);
    }

}
