/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech) (5.1.0).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package com.globant.tc.scooter.accounts.api;

import com.globant.tc.scooter.accounts.model.Credit;
import com.globant.tc.scooter.accounts.services.BuyCreditsApiDelegate;
import io.swagger.annotations.*;
import org.springframework.http.ResponseEntity;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.*;

import javax.validation.Valid;

@javax.annotation.Generated(value = "org.openapitools.codegen.languages.SpringCodegen", date = "2022-03-16T19:29:52.717+05:00[Asia/Karachi]")
@Validated
@Api(value = "buyCredits", description = "the buyCredits API")
public interface BuyCreditsApi {

    default BuyCreditsApiDelegate getDelegate() {
        return new BuyCreditsApiDelegate() {};
    }

    /**
     * POST /buyCredits : Buy credits in Mercado Pago
     *
     * @param credit  (required)
     * @return Operation success (status code 200)
     *         or Account not found (status code 404)
     */
    @ApiOperation(value = "Buy credits in Mercado Pago", nickname = "buyCreditsPost", notes = "", tags={  })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "Operation success"),
        @ApiResponse(code = 404, message = "Account not found") })
    @PostMapping(
        value = "/buyCredits",
        consumes = { "application/json" }
    )
    default ResponseEntity<Void> buyCreditsPost(@ApiParam(value = "" ,required=true )  @Valid @RequestBody Credit credit) {
        return getDelegate().buyCreditsPost(credit);
    }

}
