/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech) (5.1.0).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package com.globant.tc.scooter.accounts.api;

import com.globant.tc.scooter.accounts.model.User;
import com.globant.tc.scooter.accounts.services.FindUserByIdApiDelegate;
import io.swagger.annotations.*;
import org.springframework.http.ResponseEntity;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.*;

import javax.validation.constraints.*;

@javax.annotation.Generated(value = "org.openapitools.codegen.languages.SpringCodegen", date = "2022-03-16T19:26:49.191+05:00[Asia/Karachi]")
@Validated
@Api(value = "findUserById", description = "the findUserById API")
public interface FindUserByIdApi {

    default FindUserByIdApiDelegate getDelegate() {
        return new FindUserByIdApiDelegate() {};
    }

    /**
     * GET /findUserById/{userId} : Find a user registered in the system by the id
     *
     * @param userId id of the user (required)
     * @return OK (status code 200)
     */
    @ApiOperation(value = "Find a user registered in the system by the id", nickname = "findUserByIdUserIdGet", notes = "", response = User.class, tags={  })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "OK", response = User.class) })
    @GetMapping(
        value = "/findUserById/{userId}",
        produces = { "application/json" }
    )
    default ResponseEntity<User> findUserByIdUserIdGet(@Min(1L)@ApiParam(value = "id of the user",required=true) @PathVariable("userId") Long userId) {
        return getDelegate().findUserByIdUserIdGet(userId);
    }

}
