/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech) (5.1.0).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package com.globant.tc.scooter.accounts.api;

import com.globant.tc.scooter.accounts.services.FindUserAccountApiDelegate;
import io.swagger.annotations.*;
import org.springframework.http.ResponseEntity;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.*;

import javax.validation.constraints.*;

@javax.annotation.Generated(value = "org.openapitools.codegen.languages.SpringCodegen", date = "2022-03-16T19:29:52.717+05:00[Asia/Karachi]")
@Validated
@Api(value = "findUserAccount", description = "the findUserAccount API")
public interface FindUserAccountApi {

    default FindUserAccountApiDelegate getDelegate() {
        return new FindUserAccountApiDelegate() {};
    }

    /**
     * GET /findUserAccount/{userId} : Find an account for a redistered user
     *
     * @param userId id of the user (required)
     * @return OK (status code 200)
     *         or A user with the specified ID was not found. (status code 404)
     */
    @ApiOperation(value = "Find an account for a redistered user", nickname = "findUserAccountUserIdGet", notes = "", response = Long.class, tags={  })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "OK", response = Long.class),
        @ApiResponse(code = 404, message = "A user with the specified ID was not found.") })
    @GetMapping(
        value = "/findUserAccount/{userId}",
        produces = { "application/json" }
    )
    default ResponseEntity<Long> findUserAccountUserIdGet(@Min(1L)@ApiParam(value = "id of the user",required=true) @PathVariable("userId") Long userId) {
        return getDelegate().findUserAccountUserIdGet(userId);
    }

}
