/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech) (5.1.0).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package com.globant.tc.scooter.accounts.api;

import com.globant.tc.scooter.accounts.entity.MercadoPagoAccount;
import com.globant.tc.scooter.accounts.model.InlineObject3;
import io.swagger.annotations.*;
import org.springframework.http.ResponseEntity;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.*;

import javax.validation.Valid;

@javax.annotation.Generated(value = "org.openapitools.codegen.languages.SpringCodegen", date = "2022-03-11T21:44:36.143+05:00[Asia/Karachi]")
@Validated
@Api(value = "linkAccountToMercadoPago", description = "the linkAccountToMercadoPago API")
public interface LinkAccountToMercadoPagoApi {

    default LinkAccountToMercadoPagoApiDelegate getDelegate() {
        return new LinkAccountToMercadoPagoApiDelegate() {};
    }

    /**
     * POST /linkAccountToMercadoPago : Link account to mercado pago
     *
     * @param inlineObject3  (required)
     * @return Operation success (status code 200)
     */
    @ApiOperation(value = "Link account to mercado pago", nickname = "linkAccountToMercadoPagoPost", notes = "", tags={  })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "Operation success") })
    @PostMapping(
        value = "/linkAccountToMercadoPago",
        consumes = { "application/json" }
    )
    default ResponseEntity<MercadoPagoAccount> linkAccountToMercadoPagoPost(@ApiParam(value = "" ,required=true )  @Valid @RequestBody InlineObject3 inlineObject3) {
        return getDelegate().linkAccountToMercadoPagoPost(inlineObject3);
    }

}
