/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech) (5.1.0).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package com.globant.tc.scooter.accounts.api;

import com.globant.tc.scooter.accounts.entity.UserEntity;
import com.globant.tc.scooter.accounts.model.User;
import com.globant.tc.scooter.accounts.services.RegisterUserApiDelegate;
import io.swagger.annotations.*;
import org.springframework.http.HttpEntity;
import org.springframework.http.ResponseEntity;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.*;

import javax.validation.Valid;

@javax.annotation.Generated(value = "org.openapitools.codegen.languages.SpringCodegen", date = "2022-03-16T19:26:49.191+05:00[Asia/Karachi]")
@Validated
@Api(value = "registerUser", description = "the registerUser API")
public interface RegisterUserApi {

    default RegisterUserApiDelegate getDelegate() {
        return new RegisterUserApiDelegate() {};
    }

    /**
     * POST /registerUser : Register a User in the system
     *
     * @param user  (required)
     * @return OK (status code 200)
     */
    @ApiOperation(value = "Register a User in the system", nickname = "registerUserPost", notes = "", tags={  })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "OK") })
    @PostMapping(
        value = "/registerUser",
        consumes = { "application/json" }
    )
    default HttpEntity<?> registerUserPost(@ApiParam(value = "" ,required=true )  @Valid @RequestBody User user) {
        return  getDelegate().registerUserPost(user);
    }

}
